### PR TITLE
Introduce sass

### PR DESCRIPTION
**Pull request by michaelknoch**
i thought it would be great to use sass in your starter

### CODE REVIEW

**Comment by alicoding** [comment]
@michaelknoch Hi! Thank you so much for your PR. Is there a way to make it be an optional thing instead of removing CSS totally? I'm not familiar with sass here, but I use LESS in my project currently. I have nothing against it except I don't know what other people will think about it? :)

**Comment by michaelknoch** [comment]
i implemented two separate loaders for css and sass, now you are able to import scss or css files depending on your preference ;)

**Comment by alicoding** [comment]
yay ! \o/

Thank you so much!

**Comment by dotmagic** [comment]
I use it already, works like charm. Thanks :+1:

**Pull request merged**
