### PR TITLE
Fix indentation in package.json

### PR DESCRIPTION
**Pull request by cmmartin**

### CODE REVIEW

**Comment by cmmartin** [comment]
It turns out there are a few more. Tabs and spaces seem to be mixed in various files (index.jsx for example). You may prefer one PR that fixes them all.

**Comment by alicoding** [comment]
Hey, thank you so much for your PR. I think I should stick to one and make sure they are applied to all, but also don't know which one because I don't want to restrict people to something here. What do you think?

**Comment by cmmartin** [comment]
The tabs vs. spaces war has played out all over github thousands of times. I don't want to offer an opinion and start that war here. The only thing that matters is consistency. It looks like `index.jsx` might actually be the only other file that is mixing tabs and spaces. I will send another PR to fix that file and then everything is 💯

**Comment by alicoding** [comment]
+1 to file only consistency :) thanks for the PR again!

**Pull request merged**
