### PR TITLE
HMR fix, better global/local style path matching, updated readme

### LINKED ISSUE #182: hmr problem
if make modification is keep refreshing

### PR DESCRIPTION
**Pull request by k3a**
Fixes #182

### CODE REVIEW

**Comment by alicoding** [comment]
Is there a reason why you've picked `ejs` over `html` here?

**Comment by k3a** [comment]
yep, please pull the .production change as well. The reason is that if .html is used and you have a html loader defined, it will kick in and HtmlWebpackPlugin won't process ejs <%= %> tags in the template source. More details https://github.com/ampedandwired/html-webpack-plugin/blob/master/docs/template-option.md It's probably not "required" in your starter as you don't seem to have any html loader defined but it's safer (i got into that issue with my angular starter).

**Comment by k3a** [comment]
Alternatively we could not use any templating (no template tags), and use plain index.html, that would also work. html-webpack-plugin would just append script bundle and css bundle in that case. So it's matter of taste. ;)

**Comment by k3a** [comment]
well actually... let's use plain html, it's clearer, will make a new PR

**Pull request merged**
