### PR TITLE
Initial components

### PR DESCRIPTION
**Pull request by dhuddell**
Hey yo. look at this shit and have opinions

### CODE REVIEW

**Comment by alicoding** [comment]
Do you still like to get some opinions?

**Comment by dhuddell** [comment]
Hey! Not at the moment, but thank you! This is basically just me getting my hands dirty in react again after a long while in c#. So I'm sliiiiightly embarrassed I exposed you to this mess, BUT I'll reach back out if I want any feedback!

ps- i am aware of the uber-jankiness of the PR haha

**Comment by alicoding** [comment]
No worries! I've started way worst than this tbh :) I'm here whenever you'd like feedback :D

**Comment by dhuddell** [comment]
Ya know now that you've asked.. what's glaring at first glance?

(realizes people are on github to help and receive help)

**Comment by alicoding** [comment]
I guess it depends on the purpose of this pull request. If you were thinking of improving the current one of was just trying to create something of your own to try out? It's a bit specific now that I look at the pull request and it's hard to give feedback without much context of what you're trying to accomplish.

**Comment by dhuddell** [comment]
Yea so this PR was actually intended to go towards the start of an actual project, and was never intended to reach the source ie... wanted to clone, forked instead and then realized my PR hit you instead of just showing a buddy of mine how I intended to start our project

**Comment by dhuddell** [comment]
therein lying the wtf moment you likely had when i added all that code to be '..halping'

**Pull request closed without merging**
